# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spider.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spider.proto',
  package='spiderrpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cspider.proto\x12\tspiderrpc\"a\n\x07RssFeed\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x1a\n\x12item_content_xpath\x18\x03 \x01(\t\x12\x1b\n\x13removed_xpath_nodes\x18\x04 \x03(\t\".\n\x0cSubmitResult\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xaa\x01\n\x08\x42logFeed\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x13\n\x0b\x65ntry_xpath\x18\x03 \x01(\t\x12\x18\n\x10item_title_xpath\x18\x04 \x01(\t\x12\x17\n\x0fitem_link_xpath\x18\x05 \x01(\t\x12\x1a\n\x12item_content_xpath\x18\x06 \x01(\t\x12\x1b\n\x13removed_xpath_nodes\x18\x07 \x03(\t\"\x1c\n\nSpiderList\x12\x0e\n\x06spider\x18\x01 \x03(\t\"$\n\x0f\x43rawlTaskResult\x12\x11\n\tisrunning\x18\x01 \x01(\x08\x32\xd3\x01\n\tSpiderRpc\x12>\n\rSubmitRssFeed\x12\x12.spiderrpc.RssFeed\x1a\x17.spiderrpc.SubmitResult\"\x00\x12@\n\x0eSubmitBlogFeed\x12\x13.spiderrpc.BlogFeed\x1a\x17.spiderrpc.SubmitResult\"\x00\x12\x44\n\rCrawlArticles\x12\x15.spiderrpc.SpiderList\x1a\x1a.spiderrpc.CrawlTaskResult\"\x00\x62\x06proto3')
)




_RSSFEED = _descriptor.Descriptor(
  name='RssFeed',
  full_name='spiderrpc.RssFeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='spiderrpc.RssFeed.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='spiderrpc.RssFeed.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_content_xpath', full_name='spiderrpc.RssFeed.item_content_xpath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='removed_xpath_nodes', full_name='spiderrpc.RssFeed.removed_xpath_nodes', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=124,
)


_SUBMITRESULT = _descriptor.Descriptor(
  name='SubmitResult',
  full_name='spiderrpc.SubmitResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='spiderrpc.SubmitResult.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='spiderrpc.SubmitResult.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=172,
)


_BLOGFEED = _descriptor.Descriptor(
  name='BlogFeed',
  full_name='spiderrpc.BlogFeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='spiderrpc.BlogFeed.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category', full_name='spiderrpc.BlogFeed.category', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_xpath', full_name='spiderrpc.BlogFeed.entry_xpath', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_title_xpath', full_name='spiderrpc.BlogFeed.item_title_xpath', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_link_xpath', full_name='spiderrpc.BlogFeed.item_link_xpath', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item_content_xpath', full_name='spiderrpc.BlogFeed.item_content_xpath', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='removed_xpath_nodes', full_name='spiderrpc.BlogFeed.removed_xpath_nodes', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=345,
)


_SPIDERLIST = _descriptor.Descriptor(
  name='SpiderList',
  full_name='spiderrpc.SpiderList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spider', full_name='spiderrpc.SpiderList.spider', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=375,
)


_CRAWLTASKRESULT = _descriptor.Descriptor(
  name='CrawlTaskResult',
  full_name='spiderrpc.CrawlTaskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isrunning', full_name='spiderrpc.CrawlTaskResult.isrunning', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=413,
)

DESCRIPTOR.message_types_by_name['RssFeed'] = _RSSFEED
DESCRIPTOR.message_types_by_name['SubmitResult'] = _SUBMITRESULT
DESCRIPTOR.message_types_by_name['BlogFeed'] = _BLOGFEED
DESCRIPTOR.message_types_by_name['SpiderList'] = _SPIDERLIST
DESCRIPTOR.message_types_by_name['CrawlTaskResult'] = _CRAWLTASKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RssFeed = _reflection.GeneratedProtocolMessageType('RssFeed', (_message.Message,), dict(
  DESCRIPTOR = _RSSFEED,
  __module__ = 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spiderrpc.RssFeed)
  ))
_sym_db.RegisterMessage(RssFeed)

SubmitResult = _reflection.GeneratedProtocolMessageType('SubmitResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBMITRESULT,
  __module__ = 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spiderrpc.SubmitResult)
  ))
_sym_db.RegisterMessage(SubmitResult)

BlogFeed = _reflection.GeneratedProtocolMessageType('BlogFeed', (_message.Message,), dict(
  DESCRIPTOR = _BLOGFEED,
  __module__ = 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spiderrpc.BlogFeed)
  ))
_sym_db.RegisterMessage(BlogFeed)

SpiderList = _reflection.GeneratedProtocolMessageType('SpiderList', (_message.Message,), dict(
  DESCRIPTOR = _SPIDERLIST,
  __module__ = 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spiderrpc.SpiderList)
  ))
_sym_db.RegisterMessage(SpiderList)

CrawlTaskResult = _reflection.GeneratedProtocolMessageType('CrawlTaskResult', (_message.Message,), dict(
  DESCRIPTOR = _CRAWLTASKRESULT,
  __module__ = 'spider_pb2'
  # @@protoc_insertion_point(class_scope:spiderrpc.CrawlTaskResult)
  ))
_sym_db.RegisterMessage(CrawlTaskResult)



_SPIDERRPC = _descriptor.ServiceDescriptor(
  name='SpiderRpc',
  full_name='spiderrpc.SpiderRpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=416,
  serialized_end=627,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubmitRssFeed',
    full_name='spiderrpc.SpiderRpc.SubmitRssFeed',
    index=0,
    containing_service=None,
    input_type=_RSSFEED,
    output_type=_SUBMITRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubmitBlogFeed',
    full_name='spiderrpc.SpiderRpc.SubmitBlogFeed',
    index=1,
    containing_service=None,
    input_type=_BLOGFEED,
    output_type=_SUBMITRESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CrawlArticles',
    full_name='spiderrpc.SpiderRpc.CrawlArticles',
    index=2,
    containing_service=None,
    input_type=_SPIDERLIST,
    output_type=_CRAWLTASKRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPIDERRPC)

DESCRIPTOR.services_by_name['SpiderRpc'] = _SPIDERRPC

# @@protoc_insertion_point(module_scope)
