#! /usr/bin/env bash


if [[ ! -d www/src/static/script ]]; then
  mkdir www/src/static/script
  docker container run --volume ./www/src/static/:/home/node/build/ --workdir /home/node/build/app/ node ./build.sh
  rm -rf www/src/static/app/node_modules
fi

if [[ ! -d spider/protos ]]; then
  mkdir spider/protos/
  ln protos/spider.proto spider/protos/spider.proto
fi

if [[ ! -d spider/protos ]]; then
  mkdir www/protos/
  ln protos/spider.proto www/protos/spider.proto
fi

docker compose up --build --detach


# vim: ts=2 sw=2 sts=2 ft=bash et:

