#! /usr/bin/env bash


if podman container run --volume ./www/src/static/:/home/node/build/ --workdir /home/node/build/app/ node ./build; then
  rm -rf www/src/static/app/node_modules
fi


# vim: ts=2 sw=2 sts=2 ft=bash et:

