#! /usr/bin/env bash


if [[ ! -d www/src/static/script ]]; then
  echo "must run buildjs before build docker"
  exit
fi

if [[ ! -d spider/protos ]]; then
  mkdir spider/protos/
  ln protos/spider.proto spider/protos/spider.proto
fi

if [[ ! -d www/protos ]]; then
  mkdir www/protos/
  ln protos/spider.proto www/protos/spider.proto
fi

docker compose build


# vim: ts=2 sw=2 sts=2 ft=bash et:

