FROM python:2.7

ENV http_proxy socks5://192.168.1.135:8080
ENV https_proxy socks5://192.168.1.135:8080

RUN mkdir /spider/
ADD ./spider/requirements.txt /spider/requirements.txt
WORKDIR /spider

# RUN apt-get update
RUN pip install -r requirements.txt
RUN adduser --disabled-password --gecos '' gw
