FROM python:2.7

ENV http_proxy socks5://192.168.1.135:8080
ENV https_proxy socks5://192.168.1.135:8080

RUN mkdir /spider/
ADD ./spider/requirements.txt /spider/requirements.txt
WORKDIR /spider

# RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev python-setuptools
RUN apt-get install -y libffi-dev libxml2-dev libxslt1-dev libtiff5 libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
RUN pip install -r requirements.txt
RUN adduser --disabled-password --gecos '' spider
