FROM python:2.7

# ENV http_proxy http://103.55.27.122:8888
# ENV https_proxy http://103.55.27.122:8888

RUN mkdir /spider/
ADD ./spider/requirements.txt /spider/requirements.txt
WORKDIR /spider

RUN apt-get update
RUN pip install -r requirements.txt
RUN adduser --disabled-password --gecos '' gw
RUN mkdir /var/log/gw
RUN chown gw:gw /var/log/gw
RUN mkdir /var/run/gw
RUN chown gw:gw /var/run/gw
