#! /usr/bin/env bash


npm init -f

npm install react --save-dev
npm install react-dom --save-dev
npm install whatwg-fetch --save-dev
npm install @babel/core --save-dev
npm install @babel/preset-env --save-dev
npm install @babel/preset-react --save-dev
npm install @babel/plugin-transform-class-properties --save-dev
npm install babel-loader --save-dev
npm install webpack --save-dev
npm install webpack-cli --save-dev
npm install html-webpack-plugin --save-dev

# node_modules/.bin/webpack --mode development --config webpack.config.js
node_modules/.bin/webpack --mode production --config webpack.config.js


# vim: ts=4 sw=4 sts=4 ft=bash et:
